name: driveorbit_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  flutter_otp_text_field: ^1.1.0+2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  slide_countdown: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0
  mockito: ^5.0.16
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/